/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/partition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Document Partition */
        post: operations["change_document_partition_api_v1_documents__document_id__partition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Document */
        get: operations["preview_document_api_v1_documents__document_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reopen-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Document Review */
        post: operations["reopen_document_review_api_v1_documents__document_id__reopen_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Document */
        post: operations["review_document_api_v1_documents__document_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerSource
         * @enum {string}
         */
        AnswerSource: "internal" | "web" | "none";
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file: string;
            partition: components["schemas"]["Partition"];
            /** Title */
            title?: string | null;
        };
        /** ChangeDocumentPartitionRequest */
        ChangeDocumentPartitionRequest: {
            confirmed_partition: components["schemas"]["Partition"];
            /** Note */
            note?: string | null;
            /** Reviewer Name */
            reviewer_name?: string | null;
        };
        /** ChangeDocumentPartitionResponse */
        ChangeDocumentPartitionResponse: {
            confirmed_partition: components["schemas"]["Partition"];
            /** Document Id */
            document_id: string;
            previous_partition: components["schemas"]["Partition"];
            /** Reindexed Chunk Count */
            reindexed_chunk_count: number;
            /** Request Id */
            request_id: string;
            /** Review Note */
            review_note: string | null;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            status: components["schemas"]["DocumentStatus"];
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Allow Web Fallback
             * @default false
             */
            allow_web_fallback: boolean;
            partition_hint?: components["schemas"]["Partition"] | null;
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            answer_source: components["schemas"]["AnswerSource"];
            /** Answerable */
            answerable: boolean;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Code
             * @enum {string}
             */
            code: "OK" | "ROUTE_CLARIFICATION_REQUIRED" | "NO_INTERNAL_EVIDENCE" | "SENSITIVE_INPUT_BLOCKED";
            decision_source: components["schemas"]["DecisionSource"];
            /** Request Id */
            request_id: string;
            route: components["schemas"]["RouteName"];
            /** Searched Partitions */
            searched_partitions: components["schemas"]["Partition"][];
            /** Suggested Partitions */
            suggested_partitions: components["schemas"]["Partition"][];
            timing?: components["schemas"]["ChatTiming"];
            /** Warning */
            warning: string | null;
            /** Web Citations */
            web_citations: components["schemas"]["WebCitation"][];
        };
        /** ChatTiming */
        ChatTiming: {
            /** Answer Llm Ms */
            answer_llm_ms: number | null;
            /** Retrieval */
            retrieval: components["schemas"]["PartitionTiming"][];
            /** Router Llm Ms */
            router_llm_ms: number | null;
        };
        /** ChunkPreviewItem */
        ChunkPreviewItem: {
            /** Chunk Id */
            chunk_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            /** Preview */
            preview: string;
            /** Section Path */
            section_path: string | null;
            /** Text */
            text: string;
            /** Title */
            title: string | null;
        };
        /** ChunkPreviewResponse */
        ChunkPreviewResponse: {
            /** Chunk Count */
            chunk_count: number;
            confirmed_partition: components["schemas"]["Partition"] | null;
            /** Document Id */
            document_id: string;
            /** Items */
            items: components["schemas"]["ChunkPreviewItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            parse_quality?: components["schemas"]["ParseQualityReport"] | null;
            /** Request Id */
            request_id: string;
            selected_partition: components["schemas"]["Partition"];
            status: components["schemas"]["DocumentStatus"];
            /** Title */
            title: string | null;
            /** Total */
            total: number;
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            partition: components["schemas"]["Partition"];
            /** Section */
            section: string | null;
            /** Title */
            title: string;
        };
        /**
         * DecisionSource
         * @enum {string}
         */
        DecisionSource: "user_hint" | "llm" | "safety_fallback";
        /** DeleteDocumentResponse */
        DeleteDocumentResponse: {
            /**
             * Deleted
             * @constant
             */
            deleted: true;
            /** Document Id */
            document_id: string;
            /** Removed Chunk Count */
            removed_chunk_count: number;
            /** Request Id */
            request_id: string;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /** Chunk Count */
            chunk_count: number;
            confirmed_partition: components["schemas"]["Partition"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Mime Type */
            mime_type: string;
            /** Original Filename */
            original_filename: string;
            parse_quality?: components["schemas"]["ParseQualityReport"] | null;
            /** Request Id */
            request_id: string;
            /** Review Note */
            review_note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            selected_partition: components["schemas"]["Partition"];
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentSummaryResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Request Id */
            request_id: string;
            /** Total */
            total: number;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "parsing" | "pending_review" | "indexing" | "reindexing" | "deleting" | "ready" | "rejected" | "failed";
        /** DocumentSummaryResponse */
        DocumentSummaryResponse: {
            /** Chunk Count */
            chunk_count: number;
            confirmed_partition: components["schemas"]["Partition"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Original Filename */
            original_filename: string;
            selected_partition: components["schemas"]["Partition"];
            status: components["schemas"]["DocumentStatus"];
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Answer
             * @enum {string}
             */
            answer: "configured" | "extractive" | "not_configured";
            indexes: components["schemas"]["IndexHealth"];
            /**
             * Metadata Database
             * @enum {string}
             */
            metadata_database: "ok" | "error";
            /** Request Id */
            request_id: string;
            /**
             * Router
             * @enum {string}
             */
            router: "configured" | "not_configured";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Web Search
             * @enum {string}
             */
            web_search: "configured" | "disabled" | "not_configured";
        };
        /** IndexHealth */
        IndexHealth: {
            finance: components["schemas"]["IndexLevelHealth"];
            hr: components["schemas"]["IndexLevelHealth"];
            tech: components["schemas"]["IndexLevelHealth"];
        };
        /** IndexLevelHealth */
        IndexLevelHealth: {
            /**
             * Chunk
             * @enum {string}
             */
            chunk: "ready" | "error";
            /**
             * Document
             * @enum {string}
             */
            document: "ready" | "error";
            /**
             * Section
             * @enum {string}
             */
            section: "ready" | "error";
        };
        /** ParseQualityReport */
        ParseQualityReport: {
            /** Average Chunk Tokens */
            average_chunk_tokens: number;
            /** Blank Page Numbers */
            blank_page_numbers: number[];
            /** Chunk Count */
            chunk_count: number;
            /** Heading Recognition Rate */
            heading_recognition_rate: number;
            /** Max Chunk Tokens */
            max_chunk_tokens: number;
            /** Min Chunk Tokens */
            min_chunk_tokens: number;
            /** Near Limit Chunk Count */
            near_limit_chunk_count: number;
            /** Over Limit Chunk Count */
            over_limit_chunk_count: number;
            /** Page Count */
            page_count: number;
            partition_suggestion: components["schemas"]["PartitionSuggestion"];
            /** Section Count */
            section_count: number;
            /** Short Chunk Count */
            short_chunk_count: number;
            /**
             * Source Format
             * @enum {string}
             */
            source_format: "pdf" | "docx" | "markdown" | "text";
            /** Table Count */
            table_count: number;
            /** Titled Section Count */
            titled_section_count: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * Partition
         * @enum {string}
         */
        Partition: "finance" | "hr" | "tech";
        /** PartitionSuggestion */
        PartitionSuggestion: {
            /** Confidence */
            confidence: number;
            partition: components["schemas"]["Partition"] | null;
            /** Reasons */
            reasons: string[];
        };
        /** PartitionTiming */
        PartitionTiming: {
            /** Elapsed Ms */
            elapsed_ms: number;
            partition: components["schemas"]["Partition"];
        };
        /** ReopenDocumentReviewRequest */
        ReopenDocumentReviewRequest: {
            /** Note */
            note?: string | null;
            /** Reviewer Name */
            reviewer_name?: string | null;
        };
        /** ReopenDocumentReviewResponse */
        ReopenDocumentReviewResponse: {
            /** Confirmed Partition */
            confirmed_partition: null;
            /** Document Id */
            document_id: string;
            previous_partition: components["schemas"]["Partition"];
            /** Removed Indexed Chunk Count */
            removed_indexed_chunk_count: number;
            /** Request Id */
            request_id: string;
            /** Review Note */
            review_note: string | null;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * ReviewAction
         * @enum {string}
         */
        ReviewAction: "approve" | "reject";
        /** ReviewRequest */
        ReviewRequest: {
            action: components["schemas"]["ReviewAction"];
            confirmed_partition?: components["schemas"]["Partition"] | null;
            /** Note */
            note?: string | null;
            /** Reviewer Name */
            reviewer_name?: string | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            confirmed_partition: components["schemas"]["Partition"] | null;
            /** Document Id */
            document_id: string;
            /** Indexed Chunk Count */
            indexed_chunk_count: number;
            /** Request Id */
            request_id: string;
            /** Review Note */
            review_note: string | null;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            selected_partition: components["schemas"]["Partition"];
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * RouteName
         * @enum {string}
         */
        RouteName: "finance" | "hr" | "tech" | "composite" | "clarify";
        /** UploadDocumentResponse */
        UploadDocumentResponse: {
            /** Chunk Count */
            chunk_count: number;
            confirmed_partition: components["schemas"]["Partition"] | null;
            /** Document Id */
            document_id: string;
            /** Original Filename */
            original_filename: string;
            parse_quality: components["schemas"]["ParseQualityReport"];
            /** Request Id */
            request_id: string;
            selected_partition: components["schemas"]["Partition"];
            status: components["schemas"]["DocumentStatus"];
            /** Warnings */
            warnings: string[];
        };
        /** WebCitation */
        WebCitation: {
            /** Domain */
            domain: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DocumentStatus"] | null;
                partition?: components["schemas"]["Partition"] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteDocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_document_partition_api_v1_documents__document_id__partition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeDocumentPartitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeDocumentPartitionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_document_api_v1_documents__document_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPreviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reopen_document_review_api_v1_documents__document_id__reopen_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenDocumentReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReopenDocumentReviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_document_api_v1_documents__document_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
